// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
import { GuardError } from "@twin.org/core";
import { TenantIdContextIdHandler } from "../../src/tenantIdContextIdHandler.js";
import { TenantIdHelper } from "../../src/utils/tenantIdHelper.js";

describe("TenantIdContextIdHandler", () => {
	let handler: TenantIdContextIdHandler;

	beforeEach(() => {
		handler = new TenantIdContextIdHandler();
	});

	describe("short", () => {
		it("should convert a valid 32-character hex string to base64", () => {
			const hexValue = "0123456789abcdef0123456789abcdef";
			const result = handler.short(hexValue);

			// Verify it returns a base64 string
			expect(result).toBeDefined();
			expect(typeof result).toBe("string");
			expect(result.length).toBeGreaterThan(0);
		});

		it("should produce consistent output for the same input", () => {
			const hexValue = "a1b2c3d4e5f6789012345678abcdef90";
			const result1 = handler.short(hexValue);
			const result2 = handler.short(hexValue);

			expect(result1).toBe(result2);
		});

		it("should produce different outputs for different inputs", () => {
			const hexValue1 = "0123456789abcdef0123456789abcdef";
			const hexValue2 = "fedcba9876543210fedcba9876543210";
			const result1 = handler.short(hexValue1);
			const result2 = handler.short(hexValue2);

			expect(result1).not.toBe(result2);
		});

		it("should handle all zeros", () => {
			const hexValue = "00000000000000000000000000000000";
			const result = handler.short(hexValue);

			expect(result).toBeDefined();
			expect(typeof result).toBe("string");
		});

		it("should handle all f's", () => {
			const hexValue = "ffffffffffffffffffffffffffffffff";
			const result = handler.short(hexValue);

			expect(result).toBeDefined();
			expect(typeof result).toBe("string");
		});
	});

	describe("guard", () => {
		it("should not throw for a valid 32-character hex string", () => {
			const validHex = "0123456789abcdef0123456789abcdef";

			expect(() => handler.guard(validHex)).not.toThrow();
		});

		it("should not throw for valid hex with all lowercase", () => {
			const validHex = "abcdefabcdefabcdefabcdefabcdefab";

			expect(() => handler.guard(validHex)).not.toThrow();
		});

		it("should not throw for a tenant ID generated by TenantIdHelper", () => {
			const tenantId = TenantIdHelper.generateTenantId();

			expect(() => handler.guard(tenantId)).not.toThrow();
		});

		it("should throw GuardError for uppercase hex characters", () => {
			const validHex = "ABCDEFABCDEFABCDEFABCDEFABCDEFAB";

			expect(() => handler.guard(validHex)).toThrow(GuardError);
		});

		it("should throw GuardError for mixed case hex", () => {
			const validHex = "AbCdEf0123456789AbCdEf0123456789";

			expect(() => handler.guard(validHex)).toThrow(GuardError);
		});

		it("should throw GuardError for hex string shorter than 32 characters", () => {
			const shortHex = "0123456789abcdef";

			expect(() => handler.guard(shortHex)).toThrow(GuardError);
		});

		it("should throw GuardError for hex string longer than 32 characters", () => {
			const longHex = "0123456789abcdef0123456789abcdef00";

			expect(() => handler.guard(longHex)).toThrow(GuardError);
		});

		it("should throw GuardError for empty string", () => {
			expect(() => handler.guard("")).toThrow(GuardError);
		});

		it("should throw GuardError for non-hex characters", () => {
			const invalidHex = "0123456789abcdefghij0123456789ab";

			expect(() => handler.guard(invalidHex)).toThrow(GuardError);
		});

		it("should throw GuardError for string with spaces", () => {
			const invalidHex = "0123456789abcdef 0123456789abcde";

			expect(() => handler.guard(invalidHex)).toThrow(GuardError);
		});

		it("should throw GuardError for string with special characters", () => {
			const invalidHex = "0123456789abcdef-0123456789abcde";

			expect(() => handler.guard(invalidHex)).toThrow(GuardError);
		});
	});
});
